[package]
name = "shell-js"
version = "0.1.0"
edition = "2024"
license = "MIT"
description = "Optional WebAssembly accelerator for shell.js"
repository = "https://github.com/keys-i/shell.js"

[lib]
crate-type = ["cdylib", "rlib"]
path = "kernels/lib.rs"

[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
panic = "abort"
strip = true
